baseURL = 'https://www.warkruid.com/'
languageCode = 'en-us'
title = "Warkruid's Experiments"
theme = 'ananke'
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Warkruid's Experiments"
    weight = 1
    contentDir = "content/en"
[languages.nl]
    title = "Warkruid's Experimenten"
    weight = 1
    contentDir = "content/nl"
[languages.it]
    title = "Esperimenti di Warkruid"
    weight = 1
    contentDir = "content/it"
[languages.tok]
    title = "lipu jan Wakui"
    weight = 1
    contentDir = "content/tok"


[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = "Warkruid"
    favicon = ""
    site_logo = ""
    description = "Ramblings about technology, languages and everything else"
    background_color_class = "bg-black"
    recent_posts_number = 3

