baseURL = 'http://www.warkruid.com/'
languageCode = 'en-us'
title = "Warkruid's experiments"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

languages]
  [languages.en]
    title = "Warkruid's Experiments"
    weight = 1
    contentDir = "content/en"
  [languages.nl]
    title = "Warkruid's Experimenten"
    weight = 2
    contentDir = "content/nl"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = "Warkruid"
    favicon = ""
    site_logo = ""
    description = "Ramblings about technology and everything else"
    background_color_class = "bg-black"
    recent_posts_number = 3

