baseURL = 'https://www.warkruid.com/'
#languageCode = 'en-us'
#title = "Warkruid's Experiments"
theme = 'etch'
resourceDir = "./resources"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
    title = "Warkruid's Weeds"
    weight = 1
    contentDir = "content/en"
[languages.tok]
    title = "lipu jan Wakui"
    weight = 1
    contentDir = "content/tok"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = "Warkruid"
    favicon = ""
    site_logo = ""
    description = "Ramblings about technology, languages and everything else"
    copyright = "Copyright c 2020 Warkruid"
    dark = "auto"
    highlight = true
    background_color_class = "bg-black"
    recent_posts_number = 3
[menu]
    [[menu.main]]
       identifier = "posts"
       name = "posts"
       title = "posts"
       url = "/"
       weight = 10
    [[menu.main]]
       identifier = "about"
       name = "about"
       weight = 20
[permalinks]
    posts = "/:title/"
[markup.goldmark.renderer]
    unsafe = true
